using System.Collections.Generic;
using System.Text.Json.Serialization;
 

namespace HealthcareGraphAPI.Models
{
    public class Treatment : BaseEntity
    {
        //instances of Patient Treatment with date of treatment and follow up actions fields.
        public string Type { get; set; } = string.Empty;
        public DateTime Date { get; set; } = DateTime.UtcNow;

        // Instead of storing the full Doctor, we store only the doctor ID.
        public string DoctorId { get; set; } = string.Empty;
        public string PatientId { get; set; } = string.Empty;

        public bool Isabstract { get; set; } = false;

        // Collection of follow-up actions (e.g., Prescription, LabTest, Radiology).
        public string FollowUpAction { get; set; } = string.Empty;

        // The immutable health snapshot that is generated by the treatment event.
        public HealthSnapshot HealthSnapshot { get; set; }
    
    
}    
}